# Generated by Django 5.2 on 2025-04-14 13:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('libri', 'Libri'), ('oggettistica', 'Oggettistica'), ('cereria', 'Cereria'), ('immaginette', 'Immaginette'), ('santa_messa', 'Ostie e vino per S. Messa'), ('incenso', 'Incenso e carboncini'), ('oratorio', 'Oratorio estivo')], max_length=20)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_scontato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(upload_to='prodotti/')),
                ('lunghezza_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('larghezza_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('altezza_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('classe_spedizione', models.CharField(blank=True, choices=[('carboncini', 'Carboncini incenso'), ('libri', 'Libri'), ('oggettistica', 'Oggettistica'), ('vino', 'Vino')], max_length=20, null=True)),
                ('quantita', models.PositiveSmallIntegerField()),
                ('disponibile', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('cognome', models.CharField(blank=True, max_length=50)),
                ('ruolo', models.CharField(choices=[('amministratore', 'Amministratore'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ImmagineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='prodotti/')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='ecommerce.prodotto')),
            ],
        ),
    ]
