# Generated by Django 5.2 on 2025-04-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.URLField(blank=True)),
                ('categoria', models.CharField(choices=[('libri', 'Libri'), ('oggettistica', 'Oggettistica')], max_length=20)),
                ('sottocategoria', models.CharField(max_length=30)),
                ('quantita', models.PositiveSmallIntegerField()),
                ('disponibile', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='ImmagineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='prodotti/')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='ecommerce.prodotto')),
            ],
        ),
    ]
