# Generated by Django 5.2 on 2025-05-11 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='cap_spedizione',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='utente',
            name='citta_spedizione',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utente',
            name='data_registrazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utente',
            name='indirizzo_spedizione',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='indirizzo_spedizione_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utente',
            name='paese_spedizione',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='utente',
            name='spesa_totale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='utente',
            name='stato_spedizione',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utente',
            name='telefono_spedizione',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(choices=[('libri', 'Libri'), ('oggettistica', 'Oggettistica'), ('cereria', 'Cereria'), ('immaginette', 'Immaginette'), ('santa_messa', 'Ostie e vino per S. Messa'), ('incenso-carboncini', 'Incenso e carboncini')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='classe_spedizione',
            field=models.CharField(blank=True, choices=[('incenso-carboncini', 'Carboncini incenso'), ('libri', 'Libri'), ('oggettistica', 'Oggettistica'), ('vino', 'Vino')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.PositiveIntegerField(unique=True)),
                ('data_ordine', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('on-hold', 'In attesa'), ('completed', 'Completato'), ('cancelled', 'Cancellato'), ('refunded', 'Rimborsato')], max_length=20)),
                ('totale_spedizione', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totale_tasse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data_ordine'],
            },
        ),
    ]
