# Generated by Django 5.2 on 2025-05-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_utente_cap_spedizione_utente_citta_spedizione_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utente',
            old_name='cap_spedizione',
            new_name='cap',
        ),
        migrations.RenameField(
            model_name='utente',
            old_name='citta_spedizione',
            new_name='citta',
        ),
        migrations.RenameField(
            model_name='utente',
            old_name='indirizzo_spedizione',
            new_name='indirizzo',
        ),
        migrations.RenameField(
            model_name='utente',
            old_name='stato_spedizione',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='utente',
            old_name='paese_spedizione',
            new_name='stato',
        ),
        migrations.RenameField(
            model_name='utente',
            old_name='telefono_spedizione',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='totale_spedizione',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='totale_tasse',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='indirizzo_spedizione_2',
        ),
        migrations.CreateModel(
            name='DettaglioOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prodotto', models.CharField(max_length=255)),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='ecommerce.ordine')),
            ],
        ),
    ]
