# Generated by Django 5.2 on 2025-05-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_cap_spedizione_utente_cap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utente',
            old_name='stato',
            new_name='paese',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='spesa_totale',
        ),
        migrations.AlterField(
            model_name='utente',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
