# Generated by Django 5.2 on 2025-05-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_stato_utente_paese_remove_utente_spesa_totale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='ecommerce.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.prodotto')),
            ],
            options={
                'verbose_name': 'Elemento ordine',
                'verbose_name_plural': 'Elementi ordine',
            },
        ),
        migrations.DeleteModel(
            name='DettaglioOrdine',
        ),
    ]
