# Generated by Django 5.2 on 2025-06-14 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_ordine_data_ordine_alter_utente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ordine',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 15, 46, 2, 240596, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo_scontato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
