# Generated by Django 5.2 on 2025-06-19 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_ordine_data_ordine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ordine',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 18, 36, 55, 899772, tzinfo=datetime.timezone.utc)),
        ),
    ]
