# Generated by Django 5.2 on 2025-06-19 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_ordine_data_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ordine',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 18, 37, 4, 857222, tzinfo=datetime.timezone.utc)),
        ),
    ]
